import type { Metadata } from 'next';
import {
  Russo_One,
  Rouge_Script,
  Urbanist,
  Viga,
  Tajawal,
  Tac_One,
  Figtree,
} from 'next/font/google';
import './globals.css';
import OverallLayout from '@/layout';

const russoOne = Russo_One({
  variable: '--font-russo-one',
  subsets: ['latin'],
  weight: ['400'],
});

const rougeScript = Rouge_Script({
  variable: '--font-rouge-script',
  subsets: ['latin'],
  weight: ['400'],
});

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
});

const viga = Viga({
  variable: '--font-viga',
  subsets: ['latin'],
  weight: ['400'],
});

const tajawal = Tajawal({
  variable: '--font-tajawal',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '700', '800', '900'],
});

const tacOne = Tac_One({
  variable: '--font-tac-one',
  subsets: ['latin'],
  weight: ['400'],
});

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Decane',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${russoOne.variable} ${rougeScript.variable} ${urbanist.variable} ${viga.variable} ${tajawal.variable} ${tacOne.variable} ${figtree.variable} min-h-screen antialiased`}
      >
        <OverallLayout>{children}</OverallLayout>
      </body>
    </html>
  );
}
